"""add clicks column

Revision ID: e4fd3ee91c30
Revises: 7ac23d7eb055
Create Date: 2025-12-29 20:29:44.790982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4fd3ee91c30'
down_revision: Union[str, Sequence[str], None] = '7ac23d7eb055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('clicks', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'clicks')
    # ### end Alembic commands ###
